In [1]:
# -import library
import numpy as np

# -making array
a = np.array([5,6,7,8,9])
a

array([5, 6, 7, 8, 9])

In [2]:
# - for making all the value of array zero

b = np.zeros(2)
b

array([0., 0.])

In [3]:
# - for making all the value of array one

c = np.ones(3)
c

array([1., 1., 1.])

In [9]:
# - creating an empty array with two elemtns

d = np.empty(2)
d

array([0., 0.])

In [10]:
# - Given range to elements of array

e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [11]:
# - given array to specific range

f = np.arange(5,20)
f


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
# - continue array with intervel value

g = np.arange(3,30,3)
g

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [14]:
# - linerly spaced arrays

h = np.linspace(0,10,num=5) #- give us5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
# - give array a specific data type

i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [22]:
j = np.ones(3, dtype=np.float64)
j

array([1., 1., 1.])

# - 2D Array

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# - 3d Array

In [31]:
# - make and reshape a 3d array

c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])