# - Numpy Practice Session

# 1) - Import library in jupyter notebook

In [3]:
import numpy as np

# 2) - Creating an array using numpy

In [6]:
# 1D array
food = np.array(["Pakora","Samosa","Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [7]:
price = np.array([50,20,70])
price

array([50, 20, 70])

In [9]:
type(price)

numpy.ndarray

In [10]:
type(food)

numpy.ndarray

In [11]:
len(food)

3

In [12]:
len(price)

3

# 3) - Indexing in array

In [15]:
price[2]

70

In [17]:
food[2]

'Raita'

# 4) - Diferrent Function

In [18]:
price.mean()

46.666666666666664

# 5) - Different Methods of array

In [20]:
# -Zeros
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [21]:
# -Ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
# -empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [29]:
# -range
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [30]:
# -specify
np.arange(2,6)

array([2, 3, 4, 5])

In [31]:
# -specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
# -table of 5
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [33]:
# -line space
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
# -Specify your data type
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [35]:
# -Specify your data type
np.ones(5,dtype=np.float64)

array([1., 1., 1., 1., 1.])

# 6) -Array Functions

In [39]:
a = np.array([10,12,15,16,18,11,13,9.5])
a

array([10. , 12. , 15. , 16. , 18. , 11. , 13. ,  9.5])

In [41]:
a.sort()
a

array([ 9.5, 10. , 11. , 12. , 13. , 15. , 16. , 18. ])

In [42]:
b = np.array([10,15,20,25,30,35,40])
b

array([10, 15, 20, 25, 30, 35, 40])

In [45]:
# -concatinate or add two array
c = np.concatenate((a,b))
c

array([ 9.5, 10. , 11. , 12. , 13. , 15. , 16. , 18. , 10. , 15. , 20. ,
       25. , 30. , 35. , 40. ])

In [47]:
# -Sequence
c.sort()
c

array([ 9.5, 10. , 10. , 11. , 12. , 13. , 15. , 15. , 16. , 18. , 20. ,
       25. , 30. , 35. , 40. ])

# 2D- Array

In [48]:
a = np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [50]:
b =np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [56]:
# if you concatenate 2D array they both must have same dimension
c = np.array([[1,2,3,4,5],[5,4,3,2,1]])
c

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [55]:
d = np.array([[5,6,7,8,9],[5,4,3,2,1]])
d

array([[5, 6, 7, 8, 9],
       [5, 4, 3, 2, 1]])

In [60]:
np.concatenate((c,d),axis=0)

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [5, 6, 7, 8, 9],
       [5, 4, 3, 2, 1]])

In [61]:
np.concatenate((c,d),axis=1)

array([[1, 2, 3, 4, 5, 5, 6, 7, 8, 9],
       [5, 4, 3, 2, 1, 5, 4, 3, 2, 1]])

# 3D-Array

In [72]:
a = np.array([[[0,1,2,3,],
              [4,5,6,7]],
              
              [[0,1,2,3],
             [4,5,6,7]],
               
             [[0,1,2,3],
             [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [74]:
# -To find the number of dimesnsions
a.ndim

3

In [78]:
# -size (number of elements)
a.size

24

In [79]:
# -shape
a.shape

(3, 2, 4)

In [81]:
a = np.arange(9) # (3*3)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
# -reshape
a= a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
# -reshape
np.reshape(a, newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [88]:
# -Covert 1D to 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
a.shape

(9,)

In [90]:
# -Row Wise
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [91]:
b.shape

(1, 9)

In [92]:
# column wise
c = a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [93]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# -indexing

In [96]:
a[2:8]

array([3, 4, 5, 6, 7, 8])

In [97]:
# a array multiply with 6
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [98]:
# aarray add with plus 6
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [100]:
# -finding sum
a.sum()

45

In [101]:
# -finding mean
a.mean()

5.0